package PIM.WEBSERIVE.ACTIVITIE.STUDENT.ENTITY;
// Generated 11 �.�. 2561, 22:50:09 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccountHasActivitie generated by hbm2java
 */
@Entity
@Table(name = "account_has_activitie", catalog = "pim_activitie_student")
public class AccountHasActivitie implements java.io.Serializable {

	private AccountHasActivitieId id;
	private Account account;
	private Infoactivitie infoactivitie;
	private String accountHasActivitieStatusWork;
	private Date accountHasActivitieCreateDate;

	public AccountHasActivitie() {
	}

	public AccountHasActivitie(AccountHasActivitieId id, Account account, Infoactivitie infoactivitie) {
		this.id = id;
		this.account = account;
		this.infoactivitie = infoactivitie;
	}

	public AccountHasActivitie(AccountHasActivitieId id, Account account, Infoactivitie infoactivitie,
			String accountHasActivitieStatusWork, Date accountHasActivitieCreateDate) {
		this.id = id;
		this.account = account;
		this.infoactivitie = infoactivitie;
		this.accountHasActivitieStatusWork = accountHasActivitieStatusWork;
		this.accountHasActivitieCreateDate = accountHasActivitieCreateDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "accountId", column = @Column(name = "account_id", nullable = false)),
			@AttributeOverride(name = "infoactivitieId", column = @Column(name = "infoactivitie_id", nullable = false)) })
	public AccountHasActivitieId getId() {
		return this.id;
	}

	public void setId(AccountHasActivitieId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false, insertable = false, updatable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "infoactivitie_id", nullable = false, insertable = false, updatable = false)
	public Infoactivitie getInfoactivitie() {
		return this.infoactivitie;
	}

	public void setInfoactivitie(Infoactivitie infoactivitie) {
		this.infoactivitie = infoactivitie;
	}

	@Column(name = "account_has_activitie_status_work", length = 20)
	public String getAccountHasActivitieStatusWork() {
		return this.accountHasActivitieStatusWork;
	}

	public void setAccountHasActivitieStatusWork(String accountHasActivitieStatusWork) {
		this.accountHasActivitieStatusWork = accountHasActivitieStatusWork;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "account_has_activitie_create_date", length = 19)
	public Date getAccountHasActivitieCreateDate() {
		return this.accountHasActivitieCreateDate;
	}

	public void setAccountHasActivitieCreateDate(Date accountHasActivitieCreateDate) {
		this.accountHasActivitieCreateDate = accountHasActivitieCreateDate;
	}

}
