package PIM.WEBSERIVE.ACTIVITIE.STUDENT.ENTITY;
// Generated 11 �.�. 2561, 22:50:09 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccountHasActivitieId generated by hbm2java
 */
@Embeddable
public class AccountHasActivitieId implements java.io.Serializable {

	private int accountId;
	private int infoactivitieId;

	public AccountHasActivitieId() {
	}

	public AccountHasActivitieId(int accountId, int infoactivitieId) {
		this.accountId = accountId;
		this.infoactivitieId = infoactivitieId;
	}

	@Column(name = "account_id", nullable = false)
	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	@Column(name = "infoactivitie_id", nullable = false)
	public int getInfoactivitieId() {
		return this.infoactivitieId;
	}

	public void setInfoactivitieId(int infoactivitieId) {
		this.infoactivitieId = infoactivitieId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccountHasActivitieId))
			return false;
		AccountHasActivitieId castOther = (AccountHasActivitieId) other;

		return (this.getAccountId() == castOther.getAccountId())
				&& (this.getInfoactivitieId() == castOther.getInfoactivitieId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAccountId();
		result = 37 * result + this.getInfoactivitieId();
		return result;
	}

}
