package PIM.WEBSERIVE.ACTIVITIE.STUDENT.ENTITY;
// Generated 11 �.�. 2561, 22:50:09 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Faculty generated by hbm2java
 */
@Entity
@Table(name = "faculty", catalog = "pim_activitie_student")
public class Faculty implements java.io.Serializable {

	private Integer facultyId;
	private String facultyName;
	@JsonIgnore
	private Date facultyCreateDate;
	@JsonIgnore
	private Set<Major> majors = new HashSet<Major>(0);

	public Faculty() {
	}

	public Faculty(String facultyName) {
		this.facultyName = facultyName;
	}

	public Faculty(String facultyName, Date facultyCreateDate, Set<Major> majors) {
		this.facultyName = facultyName;
		this.facultyCreateDate = facultyCreateDate;
		this.majors = majors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "faculty_id", unique = true, nullable = false)
	public Integer getFacultyId() {
		return this.facultyId;
	}

	public void setFacultyId(Integer facultyId) {
		this.facultyId = facultyId;
	}

	@Column(name = "faculty_name", nullable = false, length = 50)
	public String getFacultyName() {
		return this.facultyName;
	}

	public void setFacultyName(String facultyName) {
		this.facultyName = facultyName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "faculty_create_date", length = 19)
	public Date getFacultyCreateDate() {
		return this.facultyCreateDate;
	}

	public void setFacultyCreateDate(Date facultyCreateDate) {
		this.facultyCreateDate = facultyCreateDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "faculty")
	public Set<Major> getMajors() {
		return this.majors;
	}

	public void setMajors(Set<Major> majors) {
		this.majors = majors;
	}

	@Override
	public String toString() {
		return "Faculty [facultyId=" + facultyId + ", facultyName=" + facultyName + ", facultyCreateDate="
				+ facultyCreateDate + ", majorsCount=" + majors.size() + "]";
	}

}
