package PIM.WEBSERIVE.ACTIVITIE.STUDENT.ENTITY;
// Generated 11 �.�. 2561, 22:50:09 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Imageactivitie generated by hbm2java
 */
@Entity
@Table(name = "imageactivitie", catalog = "pim_activitie_student")
public class Imageactivitie implements java.io.Serializable {

	private long recordactivitieId;
	private Recordactivitie recordactivitie;
	private String imageactivitieId;
	private Date imageactivitieCreateDate;

	public Imageactivitie() {
	}

	public Imageactivitie(Recordactivitie recordactivitie, String imageactivitieId) {
		this.recordactivitie = recordactivitie;
		this.imageactivitieId = imageactivitieId;
	}

	public Imageactivitie(Recordactivitie recordactivitie, String imageactivitieId, Date imageactivitieCreateDate) {
		this.recordactivitie = recordactivitie;
		this.imageactivitieId = imageactivitieId;
		this.imageactivitieCreateDate = imageactivitieCreateDate;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "recordactivitie"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "recordactivitie_id", unique = true, nullable = false)
	public long getRecordactivitieId() {
		return this.recordactivitieId;
	}

	public void setRecordactivitieId(long recordactivitieId) {
		this.recordactivitieId = recordactivitieId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Recordactivitie getRecordactivitie() {
		return this.recordactivitie;
	}

	public void setRecordactivitie(Recordactivitie recordactivitie) {
		this.recordactivitie = recordactivitie;
	}

	@Column(name = "imageactivitie_id", nullable = false, length = 50)
	public String getImageactivitieId() {
		return this.imageactivitieId;
	}

	public void setImageactivitieId(String imageactivitieId) {
		this.imageactivitieId = imageactivitieId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "imageactivitie_create_date", length = 19)
	public Date getImageactivitieCreateDate() {
		return this.imageactivitieCreateDate;
	}

	public void setImageactivitieCreateDate(Date imageactivitieCreateDate) {
		this.imageactivitieCreateDate = imageactivitieCreateDate;
	}

}
