package PIM.WEBSERIVE.ACTIVITIE.STUDENT.ENTITY;
// Generated 11 �.�. 2561, 22:50:09 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Infoactivitie generated by hbm2java
 */
@Entity
@Table(name = "infoactivitie", catalog = "pim_activitie_student")
public class Infoactivitie implements java.io.Serializable {

	private Integer infoactivitieId;
	private String infoactivitieName;
	private short infoactivitieReward;
	private Date infoactivitieTimeStart;
	private Date infoactivitieTimeEnd;
	private Date infoactivitieDateStart;
	private Date infoactivitieDateEnd;
	private String infoactivitieAddress;
	private String infoactivitieOrtherDetail;
	private byte infoactivitieNumberPersonOpen;
	private byte infoactivitieNumberPersonStatus;
	private String infoactivitieHolderName;
	private String infoactivitieHolderPhone;
	private Date infoactivitieCreateDate;
	private Set<AccountHasActivitie> accountHasActivities = new HashSet<AccountHasActivitie>(0);

	public Infoactivitie() {
	}

	public Infoactivitie(String infoactivitieName, short infoactivitieReward, Date infoactivitieTimeStart,
			Date infoactivitieTimeEnd, Date infoactivitieDateStart, Date infoactivitieDateEnd,
			String infoactivitieAddress, byte infoactivitieNumberPersonOpen, byte infoactivitieNumberPersonStatus,
			String infoactivitieHolderName, String infoactivitieHolderPhone, Date infoactivitieCreateDate) {
		this.infoactivitieName = infoactivitieName;
		this.infoactivitieReward = infoactivitieReward;
		this.infoactivitieTimeStart = infoactivitieTimeStart;
		this.infoactivitieTimeEnd = infoactivitieTimeEnd;
		this.infoactivitieDateStart = infoactivitieDateStart;
		this.infoactivitieDateEnd = infoactivitieDateEnd;
		this.infoactivitieAddress = infoactivitieAddress;
		this.infoactivitieNumberPersonOpen = infoactivitieNumberPersonOpen;
		this.infoactivitieNumberPersonStatus = infoactivitieNumberPersonStatus;
		this.infoactivitieHolderName = infoactivitieHolderName;
		this.infoactivitieHolderPhone = infoactivitieHolderPhone;
		this.infoactivitieCreateDate = infoactivitieCreateDate;
	}

	public Infoactivitie(String infoactivitieName, short infoactivitieReward, Date infoactivitieTimeStart,
			Date infoactivitieTimeEnd, Date infoactivitieDateStart, Date infoactivitieDateEnd,
			String infoactivitieAddress, String infoactivitieOrtherDetail, byte infoactivitieNumberPersonOpen,
			byte infoactivitieNumberPersonStatus, String infoactivitieHolderName, String infoactivitieHolderPhone,
			Date infoactivitieCreateDate, Set<AccountHasActivitie> accountHasActivities) {
		this.infoactivitieName = infoactivitieName;
		this.infoactivitieReward = infoactivitieReward;
		this.infoactivitieTimeStart = infoactivitieTimeStart;
		this.infoactivitieTimeEnd = infoactivitieTimeEnd;
		this.infoactivitieDateStart = infoactivitieDateStart;
		this.infoactivitieDateEnd = infoactivitieDateEnd;
		this.infoactivitieAddress = infoactivitieAddress;
		this.infoactivitieOrtherDetail = infoactivitieOrtherDetail;
		this.infoactivitieNumberPersonOpen = infoactivitieNumberPersonOpen;
		this.infoactivitieNumberPersonStatus = infoactivitieNumberPersonStatus;
		this.infoactivitieHolderName = infoactivitieHolderName;
		this.infoactivitieHolderPhone = infoactivitieHolderPhone;
		this.infoactivitieCreateDate = infoactivitieCreateDate;
		this.accountHasActivities = accountHasActivities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "infoactivitie_id", unique = true, nullable = false)
	public Integer getInfoactivitieId() {
		return this.infoactivitieId;
	}

	public void setInfoactivitieId(Integer infoactivitieId) {
		this.infoactivitieId = infoactivitieId;
	}

	@Column(name = "infoactivitie_name", nullable = false, length = 50)
	public String getInfoactivitieName() {
		return this.infoactivitieName;
	}

	public void setInfoactivitieName(String infoactivitieName) {
		this.infoactivitieName = infoactivitieName;
	}

	@Column(name = "infoactivitie_reward", nullable = false)
	public short getInfoactivitieReward() {
		return this.infoactivitieReward;
	}

	public void setInfoactivitieReward(short infoactivitieReward) {
		this.infoactivitieReward = infoactivitieReward;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "infoactivitie_time_start", nullable = false, length = 8)
	public Date getInfoactivitieTimeStart() {
		return this.infoactivitieTimeStart;
	}

	public void setInfoactivitieTimeStart(Date infoactivitieTimeStart) {
		this.infoactivitieTimeStart = infoactivitieTimeStart;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "infoactivitie_time_end", nullable = false, length = 8)
	public Date getInfoactivitieTimeEnd() {
		return this.infoactivitieTimeEnd;
	}

	public void setInfoactivitieTimeEnd(Date infoactivitieTimeEnd) {
		this.infoactivitieTimeEnd = infoactivitieTimeEnd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "infoactivitie_date_start", nullable = false, length = 10)
	public Date getInfoactivitieDateStart() {
		return this.infoactivitieDateStart;
	}

	public void setInfoactivitieDateStart(Date infoactivitieDateStart) {
		this.infoactivitieDateStart = infoactivitieDateStart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "infoactivitie_date_end", nullable = false, length = 10)
	public Date getInfoactivitieDateEnd() {
		return this.infoactivitieDateEnd;
	}

	public void setInfoactivitieDateEnd(Date infoactivitieDateEnd) {
		this.infoactivitieDateEnd = infoactivitieDateEnd;
	}

	@Column(name = "infoactivitie_address", nullable = false, length = 200)
	public String getInfoactivitieAddress() {
		return this.infoactivitieAddress;
	}

	public void setInfoactivitieAddress(String infoactivitieAddress) {
		this.infoactivitieAddress = infoactivitieAddress;
	}

	@Column(name = "infoactivitie_orther_detail", length = 200)
	public String getInfoactivitieOrtherDetail() {
		return this.infoactivitieOrtherDetail;
	}

	public void setInfoactivitieOrtherDetail(String infoactivitieOrtherDetail) {
		this.infoactivitieOrtherDetail = infoactivitieOrtherDetail;
	}

	@Column(name = "infoactivitie_number_person_open", nullable = false)
	public byte getInfoactivitieNumberPersonOpen() {
		return this.infoactivitieNumberPersonOpen;
	}

	public void setInfoactivitieNumberPersonOpen(byte infoactivitieNumberPersonOpen) {
		this.infoactivitieNumberPersonOpen = infoactivitieNumberPersonOpen;
	}

	@Column(name = "infoactivitie_number_person_status", nullable = false)
	public byte getInfoactivitieNumberPersonStatus() {
		return this.infoactivitieNumberPersonStatus;
	}

	public void setInfoactivitieNumberPersonStatus(byte infoactivitieNumberPersonStatus) {
		this.infoactivitieNumberPersonStatus = infoactivitieNumberPersonStatus;
	}

	@Column(name = "infoactivitie_holder_name", nullable = false, length = 45)
	public String getInfoactivitieHolderName() {
		return this.infoactivitieHolderName;
	}

	public void setInfoactivitieHolderName(String infoactivitieHolderName) {
		this.infoactivitieHolderName = infoactivitieHolderName;
	}

	@Column(name = "infoactivitie_holder_phone", nullable = false, length = 15)
	public String getInfoactivitieHolderPhone() {
		return this.infoactivitieHolderPhone;
	}

	public void setInfoactivitieHolderPhone(String infoactivitieHolderPhone) {
		this.infoactivitieHolderPhone = infoactivitieHolderPhone;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "infoactivitie_create_date", nullable = false, length = 19)
	public Date getInfoactivitieCreateDate() {
		return this.infoactivitieCreateDate;
	}

	public void setInfoactivitieCreateDate(Date infoactivitieCreateDate) {
		this.infoactivitieCreateDate = infoactivitieCreateDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "infoactivitie")
	public Set<AccountHasActivitie> getAccountHasActivities() {
		return this.accountHasActivities;
	}

	public void setAccountHasActivities(Set<AccountHasActivitie> accountHasActivities) {
		this.accountHasActivities = accountHasActivities;
	}

}
