package PIM.WEBSERIVE.ACTIVITIE.STUDENT.ENTITY;
// Generated 11 �.�. 2561, 22:50:09 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Major generated by hbm2java
 */
@Entity
@Table(name = "major", catalog = "pim_activitie_student")
public class Major implements java.io.Serializable {

	private Integer majorId;
	private Faculty faculty;
	private String majorName;
	@JsonIgnore
	private Date majorCreateDate;
	@JsonIgnore
	private Set<Person> persons = new HashSet<Person>(0);

	public Major() {
	}

	public Major(Faculty faculty, String majorName) {
		this.faculty = faculty;
		this.majorName = majorName;
	}

	public Major(Faculty faculty, String majorName, Date majorCreateDate, Set<Person> persons) {
		this.faculty = faculty;
		this.majorName = majorName;
		this.majorCreateDate = majorCreateDate;
		this.persons = persons;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "major_id", unique = true, nullable = false)
	public Integer getMajorId() {
		return this.majorId;
	}

	public void setMajorId(Integer majorId) {
		this.majorId = majorId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "faculty_id", nullable = false)
	public Faculty getFaculty() {
		return this.faculty;
	}

	public void setFaculty(Faculty faculty) {
		this.faculty = faculty;
	}

	@Column(name = "major_name", nullable = false, length = 50)
	public String getMajorName() {
		return this.majorName;
	}

	public void setMajorName(String majorName) {
		this.majorName = majorName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "major_create_date", length = 19)
	public Date getMajorCreateDate() {
		return this.majorCreateDate;
	}

	public void setMajorCreateDate(Date majorCreateDate) {
		this.majorCreateDate = majorCreateDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "major")
	public Set<Person> getPersons() {
		return this.persons;
	}

	public void setPersons(Set<Person> persons) {
		this.persons = persons;
	}

	@Override
	public String toString() {
		return "Major [majorId=" + majorId + ", majorName=" + majorName + "]";
	}

}
