package PIM.WEBSERIVE.ACTIVITIE.STUDENT.ENTITY;
// default package
// Generated 14 �.�. 2561, 12:11:19 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Phone generated by hbm2java
 */
@Entity
@Table(name = "phone", catalog = "pim_activitie_student")
public class Phone implements java.io.Serializable {

	private PhoneId id;
	private Person person;
	private Date phoneCreateDate;

	public Phone() {
	}

	public Phone(PhoneId id, Person person) {
		this.id = id;
		this.person = person;
	}

	public Phone(PhoneId id, Person person, Date phoneCreateDate) {
		this.id = id;
		this.person = person;
		this.phoneCreateDate = phoneCreateDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "personId", column = @Column(name = "person_id", nullable = false, length = 15)),
			@AttributeOverride(name = "phoneNumber", column = @Column(name = "phone_number", nullable = false, length = 15)) })
	public PhoneId getId() {
		return this.id;
	}

	public void setId(PhoneId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "person_id", nullable = false, insertable = false, updatable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "phone_create_date", length = 19)
	public Date getPhoneCreateDate() {
		return this.phoneCreateDate;
	}

	public void setPhoneCreateDate(Date phoneCreateDate) {
		this.phoneCreateDate = phoneCreateDate;
	}

}
