package PIM.WEBSERIVE.ACTIVITIE.STUDENT.ENTITY;
// default package
// Generated 14 �.�. 2561, 12:11:19 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PhoneId generated by hbm2java
 */
@Embeddable
public class PhoneId implements java.io.Serializable {

	private String personId;
	private String phoneNumber;

	public PhoneId() {
	}

	public PhoneId(String personId, String phoneNumber) {
		this.personId = personId;
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "person_id", nullable = false, length = 15)
	public String getPersonId() {
		return this.personId;
	}

	public void setPersonId(String personId) {
		this.personId = personId;
	}

	@Column(name = "phone_number", nullable = false, length = 15)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PhoneId))
			return false;
		PhoneId castOther = (PhoneId) other;

		return ((this.getPersonId() == castOther.getPersonId()) || (this.getPersonId() != null
				&& castOther.getPersonId() != null && this.getPersonId().equals(castOther.getPersonId())))
				&& ((this.getPhoneNumber() == castOther.getPhoneNumber())
						|| (this.getPhoneNumber() != null && castOther.getPhoneNumber() != null
								&& this.getPhoneNumber().equals(castOther.getPhoneNumber())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPersonId() == null ? 0 : this.getPersonId().hashCode());
		result = 37 * result + (getPhoneNumber() == null ? 0 : this.getPhoneNumber().hashCode());
		return result;
	}

}
