package PIM.WEBSERIVE.ACTIVITIE.STUDENT.ENTITY;
// Generated 11 �.�. 2561, 22:50:09 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Recordactivitie generated by hbm2java
 */
@Entity
@Table(name = "recordactivitie", catalog = "pim_activitie_student")
public class Recordactivitie implements java.io.Serializable {

	private Long recordactivitieId;
	private Account account;
	private String recordactivitieName;
	private String recordactivitieDo;
	private String recordactivitieAddress;
	private Date recordactivitieDatetime;
	private String recordactivitieHolderName;
	private String recordactivitieHolderPhone;
	private byte recordactivitieGetHours;
	private String recordactivitieRecordPim;
	private String recordactivitieRecordStudentloanfund;
	private String recordactivitieRecordIncomecontingentloan;
	private String recordactivitieRecordBrandambassador;
	private Date recordactivitieCreateDate;
	private Imageactivitie imageactivitie;

	public Recordactivitie() {
	}

	public Recordactivitie(Account account, String recordactivitieName, String recordactivitieDo,
			String recordactivitieAddress, Date recordactivitieDatetime, String recordactivitieHolderName,
			String recordactivitieHolderPhone, byte recordactivitieGetHours, String recordactivitieRecordPim,
			String recordactivitieRecordStudentloanfund, String recordactivitieRecordIncomecontingentloan,
			String recordactivitieRecordBrandambassador) {
		this.account = account;
		this.recordactivitieName = recordactivitieName;
		this.recordactivitieDo = recordactivitieDo;
		this.recordactivitieAddress = recordactivitieAddress;
		this.recordactivitieDatetime = recordactivitieDatetime;
		this.recordactivitieHolderName = recordactivitieHolderName;
		this.recordactivitieHolderPhone = recordactivitieHolderPhone;
		this.recordactivitieGetHours = recordactivitieGetHours;
		this.recordactivitieRecordPim = recordactivitieRecordPim;
		this.recordactivitieRecordStudentloanfund = recordactivitieRecordStudentloanfund;
		this.recordactivitieRecordIncomecontingentloan = recordactivitieRecordIncomecontingentloan;
		this.recordactivitieRecordBrandambassador = recordactivitieRecordBrandambassador;
	}

	public Recordactivitie(Account account, String recordactivitieName, String recordactivitieDo,
			String recordactivitieAddress, Date recordactivitieDatetime, String recordactivitieHolderName,
			String recordactivitieHolderPhone, byte recordactivitieGetHours, String recordactivitieRecordPim,
			String recordactivitieRecordStudentloanfund, String recordactivitieRecordIncomecontingentloan,
			String recordactivitieRecordBrandambassador, Date recordactivitieCreateDate,
			Imageactivitie imageactivitie) {
		this.account = account;
		this.recordactivitieName = recordactivitieName;
		this.recordactivitieDo = recordactivitieDo;
		this.recordactivitieAddress = recordactivitieAddress;
		this.recordactivitieDatetime = recordactivitieDatetime;
		this.recordactivitieHolderName = recordactivitieHolderName;
		this.recordactivitieHolderPhone = recordactivitieHolderPhone;
		this.recordactivitieGetHours = recordactivitieGetHours;
		this.recordactivitieRecordPim = recordactivitieRecordPim;
		this.recordactivitieRecordStudentloanfund = recordactivitieRecordStudentloanfund;
		this.recordactivitieRecordIncomecontingentloan = recordactivitieRecordIncomecontingentloan;
		this.recordactivitieRecordBrandambassador = recordactivitieRecordBrandambassador;
		this.recordactivitieCreateDate = recordactivitieCreateDate;
		this.imageactivitie = imageactivitie;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "recordactivitie_id", unique = true, nullable = false)
	public Long getRecordactivitieId() {
		return this.recordactivitieId;
	}

	public void setRecordactivitieId(Long recordactivitieId) {
		this.recordactivitieId = recordactivitieId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "recordactivitie_name", nullable = false, length = 50)
	public String getRecordactivitieName() {
		return this.recordactivitieName;
	}

	public void setRecordactivitieName(String recordactivitieName) {
		this.recordactivitieName = recordactivitieName;
	}

	@Column(name = "recordactivitie_do", nullable = false, length = 100)
	public String getRecordactivitieDo() {
		return this.recordactivitieDo;
	}

	public void setRecordactivitieDo(String recordactivitieDo) {
		this.recordactivitieDo = recordactivitieDo;
	}

	@Column(name = "recordactivitie_address", nullable = false, length = 200)
	public String getRecordactivitieAddress() {
		return this.recordactivitieAddress;
	}

	public void setRecordactivitieAddress(String recordactivitieAddress) {
		this.recordactivitieAddress = recordactivitieAddress;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "recordactivitie_datetime", nullable = false, length = 19)
	public Date getRecordactivitieDatetime() {
		return this.recordactivitieDatetime;
	}

	public void setRecordactivitieDatetime(Date recordactivitieDatetime) {
		this.recordactivitieDatetime = recordactivitieDatetime;
	}

	@Column(name = "recordactivitie_holder_name", nullable = false, length = 45)
	public String getRecordactivitieHolderName() {
		return this.recordactivitieHolderName;
	}

	public void setRecordactivitieHolderName(String recordactivitieHolderName) {
		this.recordactivitieHolderName = recordactivitieHolderName;
	}

	@Column(name = "recordactivitie_holder_phone", nullable = false, length = 15)
	public String getRecordactivitieHolderPhone() {
		return this.recordactivitieHolderPhone;
	}

	public void setRecordactivitieHolderPhone(String recordactivitieHolderPhone) {
		this.recordactivitieHolderPhone = recordactivitieHolderPhone;
	}

	@Column(name = "recordactivitie_get_hours", nullable = false)
	public byte getRecordactivitieGetHours() {
		return this.recordactivitieGetHours;
	}

	public void setRecordactivitieGetHours(byte recordactivitieGetHours) {
		this.recordactivitieGetHours = recordactivitieGetHours;
	}

	@Column(name = "recordactivitie_record_pim", nullable = false, length = 5)
	public String getRecordactivitieRecordPim() {
		return this.recordactivitieRecordPim;
	}

	public void setRecordactivitieRecordPim(String recordactivitieRecordPim) {
		this.recordactivitieRecordPim = recordactivitieRecordPim;
	}

	@Column(name = "recordactivitie_record_ studentloanfund", nullable = false, length = 5)
	public String getRecordactivitieRecordStudentloanfund() {
		return this.recordactivitieRecordStudentloanfund;
	}

	public void setRecordactivitieRecordStudentloanfund(String recordactivitieRecordStudentloanfund) {
		this.recordactivitieRecordStudentloanfund = recordactivitieRecordStudentloanfund;
	}

	@Column(name = "recordactivitie_record_incomecontingentloan", nullable = false, length = 5)
	public String getRecordactivitieRecordIncomecontingentloan() {
		return this.recordactivitieRecordIncomecontingentloan;
	}

	public void setRecordactivitieRecordIncomecontingentloan(String recordactivitieRecordIncomecontingentloan) {
		this.recordactivitieRecordIncomecontingentloan = recordactivitieRecordIncomecontingentloan;
	}

	@Column(name = "recordactivitie_record_brandambassador", nullable = false, length = 45)
	public String getRecordactivitieRecordBrandambassador() {
		return this.recordactivitieRecordBrandambassador;
	}

	public void setRecordactivitieRecordBrandambassador(String recordactivitieRecordBrandambassador) {
		this.recordactivitieRecordBrandambassador = recordactivitieRecordBrandambassador;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "recordactivitie_create_date", length = 19)
	public Date getRecordactivitieCreateDate() {
		return this.recordactivitieCreateDate;
	}

	public void setRecordactivitieCreateDate(Date recordactivitieCreateDate) {
		this.recordactivitieCreateDate = recordactivitieCreateDate;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "recordactivitie")
	public Imageactivitie getImageactivitie() {
		return this.imageactivitie;
	}

	public void setImageactivitie(Imageactivitie imageactivitie) {
		this.imageactivitie = imageactivitie;
	}

}
